sensor:
  - unique_id: "ventilation/supply_temperature"
    name: "Ventilation Supply Temperature"
    state_topic: "ventilation/supply_temperature"
    unit_of_measurement: "°C"
    value_template: "{{ value }}"
  - unique_id: "ventilation/output_temperature"
    name: "Ventilation Output Temperature"
    state_topic: "ventilation/output_temperature"
    unit_of_measurement: "°C"
    value_template: "{{ value }}"
  - unique_id: "ventilation/outside_temperature"
    name: "Ventilation Outside Temperature"
    state_topic: "ventilation/outside_temperature"
    unit_of_measurement: "°C"
    value_template: "{{ value }}"
  - unique_id: "ventilation/supply_humidity"
    name: "Ventilation Supply Humidity"
    state_topic: "ventilation/supply_humidity"
    unit_of_measurement: "%"
    value_template: "{{ value }}"
  - unique_id: "ventilation/output_humidity"
    name: "Ventilation Output Humidity"
    state_topic: "ventilation/output_humidity"
    unit_of_measurement: "%"
    value_template: "{{ value }}"
  - unique_id: "ventilation/flow_speed"
    name: "Ventilation Flow Speed"
    state_topic: "ventilation/flow_speed"
    unit_of_measurement: "m3"
    value_template: "{{ value }}"
  - unique_id: "ventilation/flow_speed_pct"
    name: "Ventilation Flow Speed Percentages"
    state_topic: "ventilation/flow_speed_pct"
    unit_of_measurement: "%"
    value_template: "{{ value }}"
  - unique_id: "ventilation/bypass_state"
    name: "Ventilation Bypass State"
    state_topic: "ventilation/bypass_state"
    value_template: "{{ value }}"
  - unique_id: "ventilation/preheater_state"
    name: "Ventilation Preheater State"
    state_topic: "ventilation/preheater_state"
    value_template: "{{ value }}"
  - unique_id: "ventilation/preheater_output"
    unit_of_measurement: "%"
    name: "Ventilation Preheater Output"
    state_topic: "ventilation/preheater_output"
    value_template: "{{ value }}"
  - unique_id: "ventilation/filter_state"
    name: "Ventilation Filter Status"
    state_topic: "ventilation/filter_state"
    value_template: "{{ value }}"
  - unique_id: "ventilation/output_pressure"
    name: "Ventilation Pressure Output"
    state_topic: "ventilation/output_pressure"
    unit_of_measurement: "pa"
  - unique_id: "ventilation/input_pressure"
    name: "Ventilation Pressure Input"
    state_topic: "ventilation/input_pressure"
    unit_of_measurement: "pa"
  - unique_id: "ventilation/filter_usage"
    name: "Filter Usage in Hours"
    state_topic: "ventilation/filter_usage"
    unit_of_measurement: "h"
    value_template: "{{ value }}"
  - unique_id: "ventilation/input_rpm"
    name: "Input RPM"
    state_topic: "ventilation/input_rpm"
    unit_of_measurement: "rpm"
  - unique_id: "ventilation/output_rpm"
    name: "Output RPM"
    state_topic: "ventilation/output_rpm"
    unit_of_measurement: "rpm"