homeassistant:
  legacy_entity_attributes: false
  legacy_triggers: false
permit_join: true
frontend:
  port: 8099
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: addons
  password: eiphegeeyieJ3she7ooc8akaeC2hahp3Pegie4bah8nuSoobae3phaihahpee8Ao
serial:
  port: /dev/ttyUSB1
devices:
  '0x00158d00010fb307':
    friendly_name: Kids room temperature
  '0x00158d00010fff77':
    friendly_name: Living room temperature
  '0x00158d0001288960':
    friendly_name: Living Room Button
  '0x00158d00012940e6':
    friendly_name: Bedroom Button
  '0x00158d00012aac6d':
    friendly_name: Kids Room Motion
  '0x00158d000159f2e1':
    friendly_name: Bedroom Temperature
  '0x00158d00016ff888':
    friendly_name: Workroom Temperature
  '0x00158d00016ff901':
    friendly_name: Bathroom Temperature
  '0x00158d0001a5e88d':
    friendly_name: Computer Button
  '0x00158d0001b1481b':
    friendly_name: Bedroom Window
  '0x00158d0001b1481f':
    friendly_name: Balcony Door
  '0x00158d0001daefa4':
    friendly_name: Entrance Door
  '0x00158d00021368eb':
    friendly_name: Test Button
  '0x847127fffedb3817':
    friendly_name: Living Room Paper
  '0x847127fffe0a9623':
    friendly_name: Server
  '0x847127fffe082e7c':
    friendly_name: Water Pump Socket
  '0xa4c1381a0101fbb5':
    friendly_name: Computer Socket
    debounce: 0
    homeassistant: {}
    optimistic: true
  '0xa4c1389a52826c4c':
    friendly_name: Living Room Socket
  '0xa4c1389e585db2ad':
    friendly_name: Kids room socket
  '0xa4c13878d8c5ae99':
    friendly_name: Bedroom Socket
  '0xa4c13847b232fa49':
    friendly_name: Washing machine socket
  '0xa4c1380de4c89031':
    friendly_name: Dryer Machine Socket
  '0xa4c13831484d04eb':
    friendly_name: Subwoofer Socket
  '0xa4c138ba74046a18':
    friendly_name: Heat Recovery Socket
  '0xa4c138ad2bd94dce':
    friendly_name: Dishwasher socket
  '0xa4c138d0d419b4d4':
    friendly_name: Fish Socket
  '0xa4c1385eba7bf270':
    friendly_name: Kitchen tempeature
  '0xa4c1385ad367dbbc':
    friendly_name: Toilet temperature
  '0xa4c138fdf794301f':
    friendly_name: Entrance hall temperature
  '0xa4c138a090e44dab':
    friendly_name: Tech Room Temperature
  '0xa4c1382edb216b1a':
    friendly_name: Terrace temperature
  '0xa4c1383a671adf4b':
    friendly_name: Fridge socket
  '0xa4c138869dc41622':
    friendly_name: '0xa4c138869dc41622'
  '0x00178801086260f3':
    friendly_name: Philips socket
  '0xa4c1382980853fdc':
    friendly_name: Air Quality
    temperature_calibration: ''
    debounce: 996
    homeassistant: {}
    optimistic: true
    debounce_ignore: []
    qos: 0
advanced:
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  last_seen: ISO_8601
